id = 'surrealdb-surrealql'
name = 'SurrealQL'
version = '0.3.0'
schema_version = 1
description = 'SurrealQL language support aligned with @surrealdb/lezer and @surrealdb/codemirror'
authors = ['SurrealDB <info@surrealdb.com>']
repository = 'https://github.com/surrealdb/surrealql-zed'

snippets = ['./snippets/surql-snippets.json']

[grammars.surrealql]
repository = 'https://github.com/surrealdb/surrealql-tree-sitter'
rev = '9e0c066be40d87514552ccdb050d86ab8073bab0'

[language_servers.surrealql-lsp]
name = 'SurrealQL Language Server'
languages = ['Surreal Query Language']
